### ISSUE TITLE
Улучшения редактора компонент

### ISSUE THREAD

**Issue by Mainkid** [Mainkid/SisyphusGameEngine#97]
1) У источников света нет параметра интенсивности света. Значение интенсивности хранится в Color.w параметре
2) При удалении слота под материал в MeshComponent движок падает
3) При создании с нуля коллайдера на объекте - тот не отображается на экране

**Comment by rosdvp** [comment]
1. Сделано
2. Сделано, но нужны правки в MeshSystem
3. Жду фиксов по физике
